# Generated by Django 4.0.6 on 2022-08-07 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('code', models.CharField(max_length=50, verbose_name='код')),
            ],
            options={
                'verbose_name': 'тип новостей',
                'verbose_name_plural': 'типы новостей',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='название статьи')),
                ('text', models.CharField(max_length=10000, verbose_name='содержание статьи')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='дата публикации')),
                ('description', models.TextField(default='', verbose_name='описание')),
                ('is_published', models.BooleanField(default=False)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_news.newstype')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
