# Generated by Django 4.0.6 on 2022-08-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(max_length=10000, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(default='', verbose_name='содержание статьи'),
        ),
    ]
