# Generated by Django 4.0.6 on 2022-08-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_alter_news_description_alter_news_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(default='', max_length=10000, verbose_name='описание'),
        ),
    ]
