# Generated by Django 2.2 on 2022-07-20 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0010_auto_20220720_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='post',
        ),
    ]
