# Generated by Django 4.0.6 on 2022-08-07 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('code', models.CharField(max_length=50, verbose_name='код')),
            ],
            options={
                'verbose_name': 'тип жилья',
                'verbose_name_plural': 'типы жилья',
            },
        ),
        migrations.CreateModel(
            name='RoomsNumberInHousingObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество комнат')),
            ],
        ),
        migrations.CreateModel(
            name='HousingObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='заголовок')),
                ('rooms_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_real_estate.roomsnumberinhousingobject')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_real_estate.housingtype')),
            ],
            options={
                'verbose_name': 'жильё',
                'verbose_name_plural': 'жильё',
            },
        ),
    ]
