# Generated by Django 4.0.6 on 2022-08-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingobject',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='описание'),
        ),
    ]
